"""Typer CLI entry point: `wechat-oracle <subcommand>`.

Production entry points include long-running processes, one-shot imports, and diagnostics:
  - `setup`             - interactive first-run .env writer
  - `doctor`            - local readiness checks
  - `run`               - start live ingest + dispatcher together
  - `init-db`           - create schema (idempotent)
  - `ingest backfill`   - one-shot import of historical export files
  - `ingest live`       - long-running SSE subscriber -> DB writer
  - `dispatcher`        - long-running DB poller -> LLM -> wx4py reply
  - `status`            - quick row count health check

Plus `weflow find` / `weflow sessions` for diagnosing WO_GROUPS resolution.

Adding a subcommand: also update README quickstart + process table
(CLAUDE.md F5; the doc-sync hook will remind you).
"""
from pathlib import Path
from collections import deque
from datetime import datetime
import os
import signal
import subprocess
import sys
import threading
import time

import httpx
import typer
from loguru import logger

from .config import settings
from .db import get_conn, init_db, transaction
from .ingest.backfill import import_file
from .ingest.writer import write_messages

app = typer.Typer(no_args_is_help=True, add_completion=False)
ingest_app = typer.Typer(no_args_is_help=True)
weflow_app = typer.Typer(no_args_is_help=True, help="Inspect what WeFlow's HTTP API exposes (diagnose WO_GROUPS issues, etc.)")
worker_app = typer.Typer(no_args_is_help=True, help="Background workers that fill in derived data on messages rows.")
verify_app = typer.Typer(no_args_is_help=True, help="Health checks for the dispatch pipeline.")
agent_app = typer.Typer(no_args_is_help=True, help="Inspect & manage agent memory (persona_drift / group_memory / run logs).")
openclaw_app = typer.Typer(no_args_is_help=True, help="OpenClaw runtime backend (the recommended agent path; uses subscription instead of per-token API).")
app.add_typer(ingest_app, name="ingest")
app.add_typer(weflow_app, name="weflow")
app.add_typer(worker_app, name="worker")
app.add_typer(verify_app, name="verify")
app.add_typer(agent_app, name="agent")
app.add_typer(openclaw_app, name="openclaw")


def _configure_stdio_utf8() -> None:
    if os.name == "nt":
        try:
            import ctypes

            ctypes.windll.kernel32.SetConsoleOutputCP(65001)
            ctypes.windll.kernel32.SetConsoleCP(65001)
        except Exception:
            pass
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            try:
                reconfigure(encoding="utf-8", errors="replace")
            except Exception:
                pass


def _env_bool(value: bool) -> str:
    return "True" if value else "False"


def _write_env(path: Path, values: dict[str, str], *, force: bool) -> None:
    if path.exists() and not force:
        typer.echo(f"{path} already exists; use --force to overwrite it.")
        raise typer.Exit(1)
    lines = [
        "# Generated by `wechat-oracle setup`.",
        "# Edit values here or override them with WO_* environment variables.",
        "",
    ]
    for key, value in values.items():
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _weflow_setup_hint() -> str:
    return (
        "Install and start WeFlow first: https://github.com/hicccc77/WeFlow\n"
        "In WeFlow, open settings, enable the HTTP API service, then copy the "
        "access token into WO_WEFLOW_TOKEN."
    )


@app.command("setup")
def setup(
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite an existing .env"),
) -> None:
    """Interactive first-run setup. Writes a minimal `.env` in the repo root."""
    env_path = Path(".env")
    if env_path.exists() and not force:
        typer.echo(f"{env_path} already exists; use --force to overwrite it.")
        raise typer.Exit(1)
    typer.echo("WeChat Oracle setup")
    typer.echo("Press Enter to accept defaults. Secrets are written only to .env.")
    typer.echo("")
    typer.echo("WeFlow is required and is not installed by this command.")
    typer.echo(_weflow_setup_hint())
    typer.echo("")

    weflow_token = typer.prompt("WeFlow token", default=settings.weflow_token or "", hide_input=True)
    groups = typer.prompt(
        "Groups to monitor (empty = all group chats exposed by WeFlow)",
        default=",".join(settings.groups),
        show_default=False,
    )
    bot_name = typer.prompt("Bot group nickname (WO_BOT_NAME)", default=settings.bot_name or "")
    reply_backend = typer.prompt(
        "Reply backend (wx4py/stdout)",
        default=settings.reply_backend or "wx4py",
    ).strip().lower()
    if reply_backend not in {"wx4py", "stdout"}:
        typer.echo("Reply backend must be 'wx4py' or 'stdout'.")
        raise typer.Exit(1)
    reply = reply_backend != "stdout"

    backend = typer.prompt(
        "Agent backend (native/openclaw)",
        default=settings.agent_backend or "native",
    ).strip().lower()
    if backend not in {"native", "openclaw"}:
        typer.echo("Agent backend must be 'native' or 'openclaw'.")
        raise typer.Exit(1)
    values: dict[str, str] = {
        "WO_WEFLOW_BASE_URL": settings.weflow_base_url,
        "WO_WEFLOW_TOKEN": weflow_token,
        "WO_GROUPS": groups,
        "WO_BOT_NAME": bot_name,
        "WO_REPLY": _env_bool(reply),
        "WO_REPLY_BACKEND": reply_backend,
        "WO_AGENT_BACKEND": backend,
        "WO_AGENT_BASE_PROBABILITY": str(settings.agent_base_probability),
        "WO_AGENT_RECENT_CONTEXT_CHAT": str(settings.agent_recent_context_chat),
        "WO_LLM_MAX_TOKENS": str(settings.llm_max_tokens),
        "WO_LLM_WRITE_MAX_TOKENS": str(settings.llm_write_max_tokens or ""),
        "WO_AGENT_LURK_ENABLED": _env_bool(settings.agent_lurk_enabled),
        "WO_AGENT_LURK_INTERVAL_SECONDS": str(settings.agent_lurk_interval_seconds),
        "WO_AGENT_LURK_MIN_NEW_MESSAGES": str(settings.agent_lurk_min_new_messages),
    }

    if backend == "openclaw":
        values.update(
            {
                "WO_OPENCLAW_GATEWAY_URL": typer.prompt(
                    "OpenClaw gateway URL",
                    default=settings.openclaw_gateway_url,
                ),
                "WO_OPENCLAW_TOKEN": typer.prompt(
                    "OpenClaw gateway token",
                    default=settings.openclaw_token or "",
                    hide_input=True,
                ),
                "WO_OPENCLAW_AGENT_ID": typer.prompt(
                    "OpenClaw agent id",
                    default=settings.openclaw_agent_id,
                ),
                "WO_OPENCLAW_TIMEOUT_SECONDS": str(settings.openclaw_timeout_seconds),
            }
        )
    else:
        values.update(
            {
                "WO_LLM_PROVIDER": settings.llm_provider,
                "WO_LLM_API_KEY": typer.prompt(
                    "LLM API key",
                    default=settings.llm_api_key or "",
                    hide_input=True,
                ),
                "WO_LLM_ENDPOINT": typer.prompt(
                    "LLM endpoint",
                    default=settings.llm_endpoint,
                ),
                "WO_LLM_MODEL": typer.prompt("LLM model", default=settings.llm_model),
                "WO_LLM_JSON_MODE": settings.llm_json_mode,
            }
        )

    if typer.confirm("Configure optional vision model for image reading?", default=False):
        values.update(
            {
                "WO_VISION_PROVIDER": settings.vision_provider,
                "WO_VISION_API_KEY": typer.prompt(
                    "Vision API key",
                    default=settings.vision_api_key or "",
                    hide_input=True,
                ),
                "WO_VISION_ENDPOINT": typer.prompt(
                    "Vision endpoint",
                    default=settings.vision_endpoint,
                ),
                "WO_VISION_MODEL": typer.prompt(
                    "Vision model",
                    default=settings.vision_model,
                ),
                "WO_VISION_MAX_IMAGES": str(settings.vision_max_images),
                "WO_VISION_MAX_TOKENS": str(settings.vision_max_tokens or ""),
            }
        )

    _write_env(env_path, values, force=force)
    init_db()
    typer.echo(f"\nwrote {env_path}")
    typer.echo("next:")
    typer.echo("  uv run wechat-oracle doctor")
    typer.echo("  uv run wechat-oracle run")


def _doctor_line(name: str, ok: bool, detail: str) -> bool:
    mark = "OK" if ok else "FAIL"
    typer.echo(f"[{mark}] {name}: {detail}")
    return ok


@app.command("doctor")
def doctor() -> None:
    """Run local readiness checks for setup, WeFlow, DB, LLM backend, and reply path."""
    failures = 0
    typer.echo("WeChat Oracle doctor\n")

    try:
        path = init_db()
        failures += not _doctor_line("database", True, str(path))
    except Exception as e:
        failures += not _doctor_line("database", False, f"{type(e).__name__}: {e}")

    failures += not _doctor_line(
        "WO_BOT_NAME",
        bool(settings.bot_name),
        repr(settings.bot_name) if settings.bot_name else "empty; mentions cannot be recognized",
    )
    failures += not _doctor_line(
        "WO_GROUPS",
        True,
        "all group chats" if not settings.groups else ", ".join(settings.groups),
    )

    if not settings.weflow_token:
        failures += not _doctor_line(
            "WeFlow API",
            False,
            "WO_WEFLOW_TOKEN is empty. " + _weflow_setup_hint().replace("\n", " "),
        )
    else:
        try:
            from .ingest.live import _build_client
            with _build_client() as client:
                resp = client.get("/api/v1/sessions", params={"limit": 5}, timeout=10.0)
                resp.raise_for_status()
                sessions = resp.json().get("sessions") or []
            failures += not _doctor_line(
                "WeFlow API",
                True,
                f"{settings.weflow_base_url} returned {len(sessions)} session(s)",
            )
        except Exception as e:
            failures += not _doctor_line(
                "WeFlow API",
                False,
                f"{type(e).__name__}: {e}. " + _weflow_setup_hint().replace("\n", " "),
            )

    backend = (settings.agent_backend or "native").lower()
    if backend == "openclaw":
        configured = bool(settings.openclaw_token and settings.openclaw_agent_id)
        failures += not _doctor_line(
            "OpenClaw config",
            configured,
            f"agent={settings.openclaw_agent_id!r} gateway={settings.openclaw_gateway_url}"
            if configured else "WO_OPENCLAW_TOKEN or WO_OPENCLAW_AGENT_ID is empty",
        )
        if configured:
            try:
                url = f"{settings.openclaw_gateway_url.rstrip('/')}/v1/chat/completions"
                payload = {
                    "model": f"openclaw/{settings.openclaw_agent_id}",
                    "messages": [{"role": "user", "content": "ping"}],
                    "max_tokens": 16,
                }
                resp = httpx.post(
                    url,
                    json=payload,
                    headers={"Authorization": f"Bearer {settings.openclaw_token}"},
                    timeout=min(30.0, settings.openclaw_timeout_seconds),
                )
                failures += not _doctor_line(
                    "OpenClaw gateway",
                    resp.status_code == 200,
                    f"HTTP {resp.status_code}",
                )
            except Exception as e:
                failures += not _doctor_line("OpenClaw gateway", False, f"{type(e).__name__}: {e}")
    else:
        failures += not _doctor_line(
            "LLM config",
            bool(settings.llm_api_key),
            f"{settings.llm_endpoint} model={settings.llm_model!r}"
            if settings.llm_api_key else "WO_LLM_API_KEY is empty",
        )

    if settings.reply and settings.reply_backend == "wx4py":
        try:
            __import__("wx4py")
            failures += not _doctor_line("reply backend", True, "wx4py import ok")
        except Exception as e:
            failures += not _doctor_line("reply backend", False, f"wx4py import failed: {e}")
    else:
        failures += not _doctor_line(
            "reply backend",
            True,
            "stdout/local only" if not settings.reply or settings.reply_backend == "stdout" else settings.reply_backend,
        )

    try:
        with get_conn() as conn:
            total = conn.execute("SELECT COUNT(*) FROM messages").fetchone()[0]
            groups = conn.execute(
                "SELECT COUNT(DISTINCT group_id) FROM messages WHERE group_id IS NOT NULL"
            ).fetchone()[0]
        _doctor_line("message archive", True, f"{total} message(s), {groups} group(s)")
    except Exception as e:
        failures += not _doctor_line("message archive", False, f"{type(e).__name__}: {e}")

    typer.echo("")
    if failures:
        typer.echo(f"doctor finished with {failures} failing check(s)")
        raise typer.Exit(1)
    typer.echo("doctor passed")


def _child_env_for_dashboard() -> dict[str, str]:
    env = dict(os.environ)
    # The parent dashboard decodes child stdout as UTF-8. On Windows, Python
    # child processes otherwise default to the active ANSI code page (often
    # cp936/GBK), which corrupts Chinese when read through the pipe.
    env.setdefault("PYTHONUTF8", "1")
    env.setdefault("PYTHONIOENCODING", "utf-8")
    return env


def _start_log_reader(
    name: str,
    proc: subprocess.Popen[str],
    log_lines: deque[str],
    lock: threading.Lock,
) -> threading.Thread:
    def read() -> None:
        assert proc.stdout is not None
        for line in proc.stdout:
            text = line.rstrip()
            if not text:
                continue
            with lock:
                log_lines.append(_dashboard_log_line(name, text))
            if _looks_like_model_call_log(text):
                try:
                    from .run_tui import request_balance_refresh

                    request_balance_refresh()
                except Exception:
                    pass

    thread = threading.Thread(target=read, name=f"wechat-oracle-{name}-log", daemon=True)
    thread.start()
    return thread


def _looks_like_model_call_log(text: str) -> bool:
    return (
        " agent:" in text
        or "agent ::" in text
        or "agent :: " in text
        or "openclaw agent ::" in text
        or "openclaw agent" in text
        or "llm_filter" in text
    )


def _dashboard_log_line(source: str, text: str) -> str:
    stamp = datetime.now().strftime("%H:%M:%S")
    return f"{stamp} {_dashboard_source_label(source)} │ {text}"


def _dashboard_source_label(source: str) -> str:
    return {
        "run": "系统",
        "live": "采集",
        "dispatcher": "调度",
        "mm": "识别",
    }.get(source, source[:4])


def _dashboard_process_label(name: str) -> str:
    return {
        "live": "采集进程",
        "dispatcher": "调度进程",
        "mm": "识别进程",
    }.get(name, name)


def _terminate_process_tree(proc: subprocess.Popen[str], *, force: bool = False) -> None:
    if proc.poll() is not None:
        return
    if os.name == "nt":
        cmd = ["taskkill", "/PID", str(proc.pid), "/T"]
        # uv/console-script wrappers keep the real Python worker as a child or
        # grandchild on Windows. Non-forced taskkill often leaves that tree
        # alive, which makes `run` sit on the shutdown deadline every time.
        cmd.append("/F")
        subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return
    if force:
        proc.kill()
    else:
        proc.send_signal(signal.SIGTERM)


@app.command("run")
def run(
    skip_init: bool = typer.Option(False, "--skip-init", help="Do not run init-db before starting"),
    plain: bool = typer.Option(False, "--plain", help="Do not start the TUI; let child processes write directly"),
) -> None:
    """Start live ingest and dispatcher together. Ctrl+C stops both."""
    _configure_stdio_utf8()
    if not skip_init:
        init_db()
    settings.ensure_dirs()
    procs: dict[str, subprocess.Popen[str]] = {}
    commands = {
        "live": ["uv", "run", "wechat-oracle", "ingest", "live"],
        "dispatcher": ["uv", "run", "wechat-oracle", "dispatcher"],
    }
    process_lock = threading.Lock()
    manual_restarts: set[str] = set()
    log_lines: deque[str] = deque(maxlen=1000)
    log_lock = threading.Lock()
    readers: list[threading.Thread] = []
    if plain:
        typer.echo("正在启动 WeChat Oracle：")

    def start_process(name: str) -> subprocess.Popen[str]:
        cmd = commands[name]
        env = _child_env_for_dashboard()
        if plain:
            typer.echo(f"  {name}: {' '.join(cmd)}")
            proc = subprocess.Popen(cmd, env=env)
        else:
            with log_lock:
                log_lines.append(
                    _dashboard_log_line("run", f"启动{_dashboard_process_label(name)}：{' '.join(cmd)}")
                )
            proc = subprocess.Popen(
                cmd,
                env=env,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding="utf-8",
                errors="replace",
                bufsize=1,
            )
            readers.append(_start_log_reader(name, proc, log_lines, log_lock))
        with process_lock:
            procs[name] = proc
        return proc

    def restart_process(name: str) -> None:
        with process_lock:
            proc = procs.get(name)
            manual_restarts.add(name)
        if proc is not None:
            with log_lock:
                log_lines.append(_dashboard_log_line("run", f"正在重启{_dashboard_process_label(name)}"))
            _terminate_process_tree(proc)
            deadline = time.time() + (2.0 if os.name == "nt" else 10.0)
            while proc.poll() is None and time.time() < deadline:
                time.sleep(0.1)
            if proc.poll() is None:
                _terminate_process_tree(proc, force=True)
        start_process(name)
        with process_lock:
            manual_restarts.discard(name)
        with log_lock:
            log_lines.append(_dashboard_log_line("run", f"{_dashboard_process_label(name)}已重启"))

    for name in commands:
        start_process(name)

    def process_rows() -> list[tuple[str, int | None, int | None]]:
        with process_lock:
            return [(name, proc.pid, proc.poll()) for name, proc in procs.items()]

    stop_requested = False
    try:
        if plain:
            while True:
                with process_lock:
                    current_procs = list(procs.items())
                for name, proc in current_procs:
                    code = proc.poll()
                    if code is not None:
                        typer.echo(
                            f"{_dashboard_process_label(name)}已退出，退出码 {code}；正在停止其他进程"
                        )
                        raise KeyboardInterrupt
                time.sleep(1.0)
        else:
            from .run_tui import RunDashboard, status_lines_for_processes
            from .config_store import (
                AgentRuntimeConfig,
                load_agent_runtime_config,
                save_agent_runtime_config,
            )

            def apply_agent_config(config: AgentRuntimeConfig) -> None:
                from .config import reload_settings

                updates = save_agent_runtime_config(config)
                os.environ.update(updates)
                reload_settings()
                with log_lock:
                    log_lines.append(
                        _dashboard_log_line(
                            "run",
                            "配置已写入 .env；正在让新的调度配置生效",
                        )
                    )
                restart_process("dispatcher")

            app = RunDashboard(
                status_provider=lambda: status_lines_for_processes(
                    process_rows(),
                    load_agent_runtime_config(),
                ),
                log_buffer=log_lines,
                agent_config_provider=load_agent_runtime_config,
                agent_config_save=apply_agent_config,
            )
            def watch_children() -> None:
                while True:
                    with process_lock:
                        current_procs = list(procs.items())
                        restarting = set(manual_restarts)
                    for child_name, child_proc in current_procs:
                        code = child_proc.poll()
                        if code is not None:
                            with process_lock:
                                if child_name in restarting or procs.get(child_name) is not child_proc:
                                    continue
                            with log_lock:
                                log_lines.append(
                                    _dashboard_log_line(
                                        "run",
                                        f"{_dashboard_process_label(child_name)}已退出，退出码 {code}；正在停止其他进程",
                                    )
                                )
                            try:
                                app.call_from_thread(app.exit)
                            except Exception:
                                pass
                            return
                    time.sleep(1.0)

            threading.Thread(
                target=watch_children,
                name="wechat-oracle-run-watch",
                daemon=True,
            ).start()
            app.run()
            stop_requested = True
    except KeyboardInterrupt:
        stop_requested = True
    finally:
        if not stop_requested and not plain:
            with log_lock:
                log_lines.append(_dashboard_log_line("run", "正在停止 WeChat Oracle..."))
        if plain:
            typer.echo("正在停止 WeChat Oracle...")
        with process_lock:
            current_procs = list(procs.values())
        for proc in current_procs:
            _terminate_process_tree(proc)
        deadline = time.time() + (2.0 if os.name == "nt" else 10.0)
        for proc in current_procs:
            while proc.poll() is None and time.time() < deadline:
                time.sleep(0.1)
            if proc.poll() is None:
                _terminate_process_tree(proc, force=True)
        if plain:
            typer.echo("已停止")
        else:
            with log_lock:
                log_lines.append(_dashboard_log_line("run", "已停止"))


@verify_app.command("roundtrip")
def verify_roundtrip() -> None:
    """Check whether WeFlow SSE echoes the bot's own replies back into the
    messages table. Required for reply-to-bot triggers and bot_wxid
    auto-discovery.

    Run this AFTER you've @ed the bot a few times in a watched group and
    the bot has replied. Reads `messages` looking for rows where
    `sender_display == WO_BOT_NAME` (i.e. the bot's own messages).
    """
    if not settings.bot_name:
        typer.echo("WARNING:  WO_BOT_NAME is empty - set it to the bot's group nickname first.")
        raise typer.Exit(1)
    init_db()
    with get_conn() as conn:
        total = conn.execute(
            "SELECT COUNT(*) AS n FROM messages WHERE sender_display = ?",
            (settings.bot_name,),
        ).fetchone()["n"]
        wxid_row = conn.execute(
            "SELECT sender_wxid FROM messages "
            "WHERE sender_display = ? AND sender_wxid IS NOT NULL AND sender_wxid != '' "
            "ORDER BY t DESC LIMIT 1",
            (settings.bot_name,),
        ).fetchone()
        recent = conn.execute(
            "SELECT msg_id, group_name, t, content_text, sender_wxid FROM messages "
            "WHERE sender_display = ? ORDER BY t DESC LIMIT 5",
            (settings.bot_name,),
        ).fetchall()

    typer.echo(f"bot_name = {settings.bot_name!r}")
    typer.echo(f"messages where sender_display matches: {total}")
    if total == 0:
        typer.echo("")
        typer.echo("ERROR: No bot messages echoed back.")
        typer.echo("   Either the bot hasn't replied yet, OR WeFlow SSE doesn't")
        typer.echo("   roundtrip self-sent messages. Reply-to-bot trigger will be")
        typer.echo("   permanently disabled in this case - set WO_BOT_WXID manually.")
        return
    if wxid_row is None:
        typer.echo("")
        typer.echo("WARNING:  Bot messages found but their sender_wxid is NULL.")
        typer.echo("   Auto-discovery can't recover wxid; set WO_BOT_WXID manually.")
    else:
        typer.echo(f"discovered bot wxid: {wxid_row['sender_wxid']}")
        if not settings.bot_wxid:
            typer.echo(f"  consider setting WO_BOT_WXID={wxid_row['sender_wxid']} in .env")
            typer.echo("    (skips the wxid discovery delay on cold start)")
        elif settings.bot_wxid != wxid_row["sender_wxid"]:
            typer.echo(f"WARNING:  WO_BOT_WXID={settings.bot_wxid!r} but DB shows {wxid_row['sender_wxid']!r}")
    typer.echo("")
    typer.echo("recent bot messages:")
    from datetime import datetime
    for r in recent:
        ts = datetime.fromtimestamp(int(r["t"])).strftime("%Y-%m-%d %H:%M")
        body = (r["content_text"] or "").replace("\n", " ")[:60]
        typer.echo(f"  [{r['msg_id']}] {ts} ({r['group_name'] or '?'}): {body}")


@worker_app.command("mm")
def worker_mm() -> None:
    """Standalone OCR/ASR worker. Usually you don't need to run this - `ingest
    live` already starts an mm worker thread alongside SSE capture, so a
    normal "live + dispatcher" deployment covers it.

    Use this command when you want to run mm on its own - e.g. to drain a
    backfill queue without ingesting new messages, or to debug OCR/ASR in
    isolation. Long-running. Polls newest-first. Models lazy-load on first
    use: rapidocr-onnxruntime for images, faster-whisper (`small` by default;
    set WO_WHISPER_MODEL=tiny|base|medium|large-v3 to override) for voice.
    Both run locally on CPU - no data leaves the machine.
    """
    from .log_utils import setup_process_log
    from .worker.mm import run_mm_worker
    setup_process_log("mm")
    run_mm_worker()


@app.command("init-db")
def init_db_cmd() -> None:
    """Create / migrate the SQLite database."""
    path = init_db()
    logger.info("db ready at {}", path)


@ingest_app.command("backfill")
def ingest_backfill(
    path: Path = typer.Argument(..., exists=True, readable=True, dir_okay=False),
    fmt: str = typer.Option("jsonl", "--format", "-f", help="weflow | jsonl"),
) -> None:
    """Import a historical export file into the messages table."""
    init_db()
    settings.ensure_dirs()
    msgs = import_file(path, fmt, settings.data_dir)
    with get_conn() as conn:
        attempted, inserted = write_messages(conn, msgs)
    typer.echo(f"backfill: attempted={attempted} new={inserted}")


@ingest_app.command("live")
def ingest_live() -> None:
    """Subscribe to WeFlow SSE for new messages in WO_GROUPS, AND run the mm
    OCR/ASR worker in a background thread. Requires WeFlow running.

    Combined process so a normal deployment is just two terminals:
    `ingest live` (this) + `dispatcher`. The mm thread shares the SQLite
    file via WAL - no separate process needed.
    """
    from .ingest.live import run_live
    from .log_utils import setup_process_log
    setup_process_log("live")
    run_live()


@app.command("dispatcher")
def dispatcher_cmd() -> None:
    """Watch DB for `@<bot> /find ...` commands; print results to stdout + log.

    Requires WO_BOT_NAME and WO_LLM_API_KEY in .env. Runs in foreground;
    Ctrl+C to stop. Safe to run alongside `ingest live`.
    """
    from .dispatcher import run_dispatcher
    from .log_utils import setup_process_log
    setup_process_log("dispatcher")
    run_dispatcher()


# --- agent memory inspection ----------------------------------------------


@agent_app.command("show")
def agent_show(
    group_id: str = typer.Argument(..., help="messages.group_id of the target group"),
) -> None:
    """Dump persona_drift + group_memory + lurk cursor for one group."""
    from datetime import datetime
    init_db()
    with get_conn() as conn:
        drift = conn.execute(
            "SELECT drift_text, updated_at, last_run_id FROM persona_drift WHERE group_id=?",
            (group_id,),
        ).fetchone()
        memory = conn.execute(
            "SELECT notes_text, size_chars, updated_at, last_run_id FROM group_memory WHERE group_id=?",
            (group_id,),
        ).fetchone()
        lurk_state = conn.execute(
            "SELECT last_msg_id, last_run_id, updated_at FROM agent_lurk_state WHERE group_id=?",
            (group_id,),
        ).fetchone()

    typer.echo(f"=== group_id={group_id!r} ===\n")
    typer.echo("--- persona_drift ---")
    if drift is None or not (drift["drift_text"] or "").strip():
        typer.echo("(empty)\n")
    else:
        ts = datetime.fromtimestamp(drift["updated_at"]).strftime("%Y-%m-%d %H:%M") if drift["updated_at"] else "?"
        typer.echo(f"updated_at={ts}  last_run_id={drift['last_run_id'] or '?'}")
        typer.echo(drift["drift_text"])
        typer.echo("")

    cap = settings.agent_memory_max_chars
    typer.echo(f"--- group_memory (cap {cap} chars) ---")
    if memory is None or not (memory["notes_text"] or "").strip():
        typer.echo("(empty)\n")
    else:
        ts = datetime.fromtimestamp(memory["updated_at"]).strftime("%Y-%m-%d %H:%M") if memory["updated_at"] else "?"
        size = memory["size_chars"] or 0
        pct = size * 100 // cap if cap else 0
        typer.echo(
            f"updated_at={ts}  last_run_id={memory['last_run_id'] or '?'}  "
            f"size={size} chars ({pct}% of cap)"
        )
        typer.echo(memory["notes_text"])

    typer.echo("\n--- lurk_state ---")
    if lurk_state is None:
        typer.echo("(no cursor yet)")
    else:
        ts = datetime.fromtimestamp(lurk_state["updated_at"]).strftime("%Y-%m-%d %H:%M") if lurk_state["updated_at"] else "?"
        typer.echo(
            f"last_msg_id={lurk_state['last_msg_id'] or '?'}  "
            f"last_run_id={lurk_state['last_run_id'] or '?'}  updated_at={ts}"
        )


@agent_app.command("wipe")
def agent_wipe(
    group_id: str = typer.Argument(..., help="messages.group_id of the target group"),
    yes: bool = typer.Option(False, "--yes", "-y", help="Skip confirmation prompt"),
    persona_only: bool = typer.Option(False, "--persona-only", help="Wipe persona_drift only, keep group_memory"),
    memory_only: bool = typer.Option(False, "--memory-only", help="Wipe group_memory only, keep persona_drift"),
) -> None:
    """Clear persona_drift and/or group_memory for one group. Destructive -
    bot resets to its defaults in this group. agent_run_log is NOT touched
    (audit trail stays).
    """
    if persona_only and memory_only:
        typer.echo("WARNING:  --persona-only and --memory-only are mutually exclusive")
        raise typer.Exit(1)
    targets = []
    if not memory_only:
        targets.append("persona_drift")
    if not persona_only:
        targets.append("group_memory")
    if not yes:
        typer.echo(f"about to clear {', '.join(targets)} for group_id={group_id!r}")
        confirm = typer.confirm("proceed?")
        if not confirm:
            typer.echo("aborted")
            raise typer.Exit(0)
    init_db()
    with get_conn() as conn:
        with transaction(conn):
            if "persona_drift" in targets:
                conn.execute("DELETE FROM persona_drift WHERE group_id=?", (group_id,))
            if "group_memory" in targets:
                conn.execute("DELETE FROM group_memory WHERE group_id=?", (group_id,))
    typer.echo(f"wiped: {', '.join(targets)}")


@agent_app.command("lurk")
def agent_lurk(
    group_id: str = typer.Argument(..., help="messages.group_id of the target group"),
) -> None:
    """One-shot 'lurk' run: bot reads new messages since its cursor, may
    search older history for context, and decides whether to update
    group_memory / persona_drift. No reply is ever sent to the group.

    Useful for periodic background memory consolidation (cron this every
    30 min for an active group), or to manually nudge the bot to update
    its impression of group activity after you've imported a backfill.
    """
    from .agent.orchestrator import chat_via_lurk
    from .dispatcher import _build_llm_client, _resolve_bot_wxid
    if not settings.bot_name:
        typer.echo("WARNING:  WO_BOT_NAME is empty - set it before lurking.")
        raise typer.Exit(1)
    init_db()
    settings.ensure_dirs()
    log_path = settings.data_dir / "dispatcher.log"
    llm_log_path = settings.data_dir / "llm_debug.log"
    llm = _build_llm_client()
    with get_conn() as conn:
        bot_wxid = _resolve_bot_wxid(conn, settings.bot_name)
        # Find the group_name for the prompt; OK if missing.
        row = conn.execute(
            "SELECT group_name FROM messages WHERE group_id=? AND group_name IS NOT NULL "
            "ORDER BY t DESC LIMIT 1",
            (group_id,),
        ).fetchone()
        group_name = row["group_name"] if row else None
        trace_block = chat_via_lurk(
            conn=conn,
            llm=llm,
            model=settings.llm_model,
            bot_name=settings.bot_name,
            bot_wxid=bot_wxid,
            group_id=group_id,
            group_name=group_name,
            log_path=log_path,
            llm_log_path=llm_log_path,
        )
    typer.echo(trace_block)


@agent_app.command("ask")
def agent_ask(
    group: str = typer.Argument(..., help="Target group id, group name, or unique fragment"),
    question: list[str] = typer.Argument(..., help="Question/task text"),
    write: bool = typer.Option(
        False,
        "--write",
        help="Allow the local turn to update group_memory / persona_drift",
    ),
    trace: bool = typer.Option(False, "--trace", help="Print the agent trace after the reply"),
) -> None:
    """Ask the agent about one group locally. No WeChat reply is sent."""
    from .agent.local_ask import run_local_ask

    text = " ".join(question).strip()
    if not text:
        typer.echo("question is empty")
        raise typer.Exit(1)
    result = run_local_ask(
        group_selector=group,
        question=text,
        allow_writes=write,
        log_path=settings.data_dir / "dispatcher.log",
        llm_log_path=settings.data_dir / "llm_debug.log",
    )
    typer.echo(f"group: {result.group.label}")
    typer.echo(f"mode: {'local_task/write' if result.allow_writes else 'local_ask/read-only'}")
    typer.echo(f"duration: {result.duration_s:.1f}s")
    typer.echo("")
    typer.echo(result.reply_text or "(no reply)")
    if trace and result.trace_block:
        typer.echo("\n--- trace ---")
        typer.echo(result.trace_block)


def _classify_silent(phase_a_trace: list[dict[str, object]] | None) -> tuple[str, str]:
    """Categorize why an agent run ended without a reply. Returns (label, detail).
    Labels: 'stay_silent' (A) / 'empty' (B) / 'max_steps' (C) / 'unknown'."""
    if not phase_a_trace:
        return "unknown", ""
    # A: explicit termination via stay_silent
    for s in phase_a_trace:
        if s.get("kind") == "terminate" and s.get("reason") == "stay_silent":
            # Reason given by the model lives in the prior tool_call args
            for prior in phase_a_trace:
                if prior.get("kind") == "tool_call" and prior.get("tool") == "stay_silent":
                    args = prior.get("args") or {}
                    return "stay_silent", str(args.get("reason", ""))[:80]
            return "stay_silent", ""
    # C: hit the step cap
    for s in phase_a_trace:
        if s.get("kind") == "max_steps_hit":
            return "max_steps", ""
    # B: a final step with empty content
    for s in phase_a_trace:
        if s.get("kind") == "final" and not s.get("content"):
            retried = any(t.get("kind") == "empty_final_retry" for t in phase_a_trace)
            return "empty", "(retried once)" if retried else ""
    return "unknown", ""


@agent_app.command("show-runs")
def agent_show_runs(
    group_id: str = typer.Argument(..., help="messages.group_id of the target group"),
    limit: int = typer.Option(10, "--limit", "-n"),
) -> None:
    """Recent agent_run_log entries with phase-B writes highlighted.

    Silent runs are tagged with one of three causes:
      stay_silent: model called the stay_silent tool (healthy decision)
      empty:       model returned empty final text without calling stay_silent
                   (likely confused / refused - investigate the trigger msg)
      max_steps:   model burned all tool-calling rounds without emitting text
                   (rare since runtime forces final on last step)
    """
    import json as _json
    from datetime import datetime
    from .agent.memory import list_recent_runs
    init_db()
    with get_conn() as conn:
        rows = list_recent_runs(conn, group_id, limit=limit)
    if not rows:
        typer.echo(f"no agent runs for group_id={group_id!r}")
        return
    for r in rows:
        ts = datetime.fromtimestamp(r["started_at"]).strftime("%Y-%m-%d %H:%M:%S") if r["started_at"] else "?"
        dur = (r["finished_at"] - r["started_at"]) if (r["started_at"] and r["finished_at"]) else 0
        reply_text = r["reply_text"]
        if r["trigger_kind"] == "lurk":
            reply = "(lurk: no chat reply)"
        elif reply_text is None or not reply_text.strip():
            try:
                pa = _json.loads(r["phase_a_trace"] or "[]")
            except _json.JSONDecodeError:
                pa = []
            label, detail = _classify_silent(pa)
            reply = f"(silent: {label}{' - ' + detail if detail else ''})"
        else:
            reply = reply_text.replace("\n", " ")[:80]
        typer.echo(
            f"[{r['run_id']}] {ts}  trigger={r['trigger_kind']:12s}  "
            f"msg_id={r['trigger_msg_id'] or '?':>7}  {dur:.1f}s"
        )
        typer.echo(f"     reply: {reply}")
        # Surface any Phase B writes inline
        try:
            pb = _json.loads(r["phase_b_trace"] or "[]")
        except _json.JSONDecodeError:
            pb = []
        writes = [s for s in pb if s.get("kind") == "tool_call" and s.get("tool", "").startswith("update_")]
        for w in writes:
            args = w.get("args", {})
            preview_key = "drift_text" if w["tool"] == "update_persona_drift" else "notes_text"
            preview = (args.get(preview_key, "") or "").replace("\n", " ")[:80]
            typer.echo(f"     phase B {w['tool']}: {preview}")


@weflow_app.command("find")
def weflow_find(keyword: str = typer.Argument(..., help="Group name / remark / wxid fragment")) -> None:
    """Search both /api/v1/contacts and /api/v1/sessions for a group. Use this to find
    the correct wxid to put in WO_GROUPS when a name doesn't resolve."""
    from .ingest.live import _build_client
    with _build_client() as client:
        cresp = client.get("/api/v1/contacts", params={"keyword": keyword, "limit": 50})
        cresp.raise_for_status()
        contacts = cresp.json().get("contacts") or []
        groups = [c for c in contacts if "@chatroom" in (c.get("username") or "")]
        people = [c for c in contacts if "@chatroom" not in (c.get("username") or "")]

        sresp = client.get("/api/v1/sessions", params={"keyword": keyword, "limit": 50})
        sresp.raise_for_status()
        sessions = sresp.json().get("sessions") or []

        typer.echo(f"contacts (groups): {len(groups)}")
        for c in groups:
            typer.echo(
                f"  username={c.get('username')}  "
                f"nick={c.get('nickname')!r}  remark={c.get('remark')!r}  "
                f"display={c.get('displayName')!r}"
            )
        typer.echo(f"\ncontacts (people): {len(people)}")
        for c in people[:10]:
            typer.echo(
                f"  username={c.get('username')}  "
                f"nick={c.get('nickname')!r}  remark={c.get('remark')!r}"
            )
        typer.echo(f"\nsessions: {len(sessions)}")
        for s in sessions[:20]:
            typer.echo(
                f"  username={s.get('username')}  display={s.get('displayName')!r}  "
                f"type={s.get('sessionType')}"
            )


@weflow_app.command("sessions")
def weflow_sessions(
    keyword: str = typer.Option("", "--keyword", "-k", help="Filter by username/displayName substring"),
    limit: int = typer.Option(10000, "--limit", "-n"),
    only_groups: bool = typer.Option(False, "--groups-only", help="Only list @chatroom sessions"),
) -> None:
    """List sessions WeFlow knows about. Use this to find the exact name or wxid for WO_GROUPS."""
    from .ingest.live import _build_client
    with _build_client() as client:
        params: dict[str, str | int] = {"limit": limit}
        if keyword:
            params["keyword"] = keyword
        resp = client.get("/api/v1/sessions", params=params)
        resp.raise_for_status()
        sessions = resp.json().get("sessions", []) or []
        if only_groups:
            sessions = [s for s in sessions if "@chatroom" in (s.get("username") or "")]
        typer.echo(f"{len(sessions)} sessions:")
        for s in sessions:
            display = s.get("displayName") or "?"
            kind = s.get("sessionType") or "?"
            user = s.get("username") or "?"
            typer.echo(f"  {kind:8s}  {display!r:40s}  {user}")


@openclaw_app.command("mcp-test")
def openclaw_mcp_test() -> None:
    """End-to-end smoke test: spawn `mcp-serve` as a subprocess, do the MCP
    initialize handshake over stdio, list tools, then call search_group_messages
    on the busiest group. This is what OpenClaw will do under the hood - if
    THIS works and OpenClaw still doesn't see the tools, the bug is on
    OpenClaw's side (registration/profile/restart), not ours.
    """
    import asyncio
    import json as _json
    import os
    import sys
    from mcp import ClientSession  # type: ignore[import-untyped]
    from mcp.client.stdio import StdioServerParameters, stdio_client  # type: ignore[import-untyped]

    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8", errors="replace")

    # Resolve a real group_id BEFORE we start the async session, so database
    # access errors surface with a normal traceback instead of getting buried
    # inside an asyncio TaskGroup ExceptionGroup.
    typer.echo("[0/4] open SQLite ...")
    try:
        with get_conn() as conn:
            db_row = conn.execute(
                "SELECT group_id FROM messages WHERE group_id IS NOT NULL "
                "GROUP BY group_id ORDER BY COUNT(*) DESC LIMIT 1"
            ).fetchone()
            img_row = conn.execute(
                "SELECT msg_id, group_id FROM messages "
                "WHERE type='image' AND media_path IS NOT NULL "
                "ORDER BY msg_id DESC LIMIT 1"
            ).fetchone()
    except Exception as e:
        typer.echo(f"      [ERR] cannot open/read DB at {settings.db_path}: {type(e).__name__}: {e}")
        typer.echo("      Check that the MCP server cwd points at this checkout and that the DB is not locked.")
        raise typer.Exit(2)
    test_gid = db_row["group_id"] if db_row else None
    typer.echo(f"      OK; busiest group_id={test_gid!r}")
    if img_row is not None:
        typer.echo(f"      latest image row: msg_id={img_row['msg_id']} group_id={img_row['group_id']!r}")

    async def run() -> None:
        # mcp.client.stdio does NOT inherit parent env by default, so pass it
        # through explicitly for PATH/HOME/etc. used by the spawned `uv run`.
        params = StdioServerParameters(
            command="uv",
            args=["run", "wechat-oracle", "openclaw", "mcp-serve"],
            env=dict(os.environ),
        )
        async with stdio_client(params) as (read, write):
            async with ClientSession(read, write) as session:
                typer.echo("[1/4] initialize ...")
                init = await session.initialize()
                typer.echo(f"      server: {init.serverInfo.name} v{init.serverInfo.version}")
                typer.echo(f"      protocol: {init.protocolVersion}")

                typer.echo("[2/4] list tools (with raw schemas) ...")
                tools_resp = await session.list_tools()
                typer.echo(f"      got {len(tools_resp.tools)} tools.")
                for t in tools_resp.tools:
                    in_schema = getattr(t, "inputSchema", None)
                    out_schema = getattr(t, "outputSchema", None)
                    typer.echo(f"      -- {t.name} --")
                    in_str = _json.dumps(in_schema, ensure_ascii=False) if in_schema else "(none)"
                    out_str = _json.dumps(out_schema, ensure_ascii=False) if out_schema else "(none)"
                    typer.echo(f"        inputSchema:  {in_str[:300]}")
                    typer.echo(f"        outputSchema: {out_str[:300]}")

                if test_gid is None:
                    typer.echo("[3/4] skip search_group_messages call - no groups in DB")
                else:
                    typer.echo(f"[3/4] search_group_messages(group_id={test_gid!r}, query='', limit=2) ...")
                    result = await session.call_tool(
                        "search_group_messages",
                        {"group_id": test_gid, "query": "", "limit": 2},
                    )
                    for c in result.content:
                        text = getattr(c, "text", None)
                        if text:
                            typer.echo("      " + text.replace("\n", "\n      ")[:300])

                if img_row is None:
                    typer.echo("[4/4] skip load_image - no image rows with media_path in DB")
                else:
                    typer.echo(
                        f"[4/4] load_image(group_id={img_row['group_id']!r}, "
                        f"msg_id={img_row['msg_id']}) ..."
                    )
                    img_result = await session.call_tool(
                        "load_image",
                        {"group_id": img_row["group_id"], "msg_id": int(img_row["msg_id"])},
                    )
                    typer.echo(f"      isError={getattr(img_result, 'isError', None)}")
                    typer.echo(f"      content blocks: {len(img_result.content)}")
                    for i, c in enumerate(img_result.content):
                        kind = type(c).__name__
                        bits = []
                        for attr in ("type", "mimeType"):
                            if hasattr(c, attr):
                                bits.append(f"{attr}={getattr(c, attr)!r}")
                        if hasattr(c, "data"):
                            d = c.data
                            bits.append(f"data_len={len(d) if isinstance(d, str) else '?'}")
                        if hasattr(c, "text"):
                            bits.append(f"text={c.text[:80]!r}")
                        typer.echo(f"      content[{i}]: {kind}  " + "  ".join(bits))
        typer.echo("\n[OK] our MCP server works end-to-end via stdio.")

    try:
        asyncio.run(run())
    except BaseExceptionGroup as eg:  # type: ignore[name-defined]  # 3.11+
        typer.echo(f"\n[ERR] ExceptionGroup of {len(eg.exceptions)} sub-exception(s):")
        for i, sub in enumerate(eg.exceptions, 1):
            typer.echo(f"  ({i}) {type(sub).__name__}: {sub}")
            inner = getattr(sub, "exceptions", None)
            if inner:
                for j, deeper in enumerate(inner, 1):
                    typer.echo(f"      .{j} {type(deeper).__name__}: {deeper}")
        raise typer.Exit(2)
    except Exception as e:
        typer.echo(f"\n[ERR] {type(e).__name__}: {e}")
        raise typer.Exit(2)


@openclaw_app.command("mcp-serve")
def openclaw_mcp_serve() -> None:
    """Start the MCP server that exposes WeChat-Oracle tools to OpenClaw's
    wechat-bot agent. Stdio-based - meant to be spawned by OpenClaw's MCP
    client. Register on the OpenClaw side roughly like:

      openclaw mcp set wechat-oracle \\
        --command "uv" --args "run wechat-oracle openclaw mcp-serve"

    Exposes the full OpenClaw tool surface: history search, quote/forward
    expansion, media reads, and memory/persona read-write tools.
    """
    from .mcp_server import run_mcp_server
    run_mcp_server()


@openclaw_app.command("ping")
def openclaw_ping(
    message: str = typer.Argument("ping", help="Text to send"),
    timeout: float = typer.Option(120.0, "--timeout", "-t", help="HTTP timeout in seconds"),
) -> None:
    """Smoke-test the OpenClaw chat-completions endpoint with the configured
    agent. Prints HTTP status, latency, and the assistant reply (or error).

    Note: a real wechat-bot agent with full skills loaded can have prompt
    sizes in the 10-50K range. First call typically takes 20-40s. Default
    timeout is 120s; raise with --timeout if your agent is heavier.
    """
    import time as _time
    import sys as _sys
    import httpx
    if not settings.openclaw_token:
        typer.echo("WARNING:  WO_OPENCLAW_TOKEN is empty - set it to the gateway's auth token.")
        raise typer.Exit(1)
    url = f"{settings.openclaw_gateway_url.rstrip('/')}/v1/chat/completions"
    payload = {
        "model": f"openclaw/{settings.openclaw_agent_id}",
        "messages": [{"role": "user", "content": message}],
    }
    headers = {"Authorization": f"Bearer {settings.openclaw_token}"}
    typer.echo(f"POST {url}  model={payload['model']!r}")
    typer.echo(f"(waiting up to {timeout:.0f}s for response - first call to a heavy agent can take 20-40s)")
    _sys.stdout.flush()
    t0 = _time.time()
    try:
        resp = httpx.post(url, json=payload, headers=headers, timeout=timeout)
    except httpx.HTTPError as e:
        typer.echo(f"[ERR] HTTP error after {_time.time() - t0:.1f}s: {e}")
        raise typer.Exit(2)
    dt = _time.time() - t0
    typer.echo(f"HTTP {resp.status_code}  dt={dt:.2f}s")
    if resp.status_code != 200:
        typer.echo(f"body: {resp.text[:600]}")
        raise typer.Exit(2)
    body = resp.json()
    choices = body.get("choices") or []
    if not choices:
        typer.echo(f"WARNING:  no choices in response: {body}")
        raise typer.Exit(2)
    reply = (choices[0].get("message") or {}).get("content") or ""
    usage = body.get("usage") or {}
    typer.echo(f"reply: {reply!r}")
    if usage:
        typer.echo(f"usage: {usage}")


@app.command("status")
def status() -> None:
    """Quick health check: db row counts."""
    init_db()
    with get_conn() as conn:
        total = conn.execute("SELECT COUNT(*) FROM messages").fetchone()[0]
        per_status = conn.execute(
            "SELECT status, COUNT(*) FROM messages GROUP BY status"
        ).fetchall()
        per_group = conn.execute(
            "SELECT group_name, COUNT(*) FROM messages GROUP BY group_name"
        ).fetchall()
    typer.echo(f"db: {settings.db_path}")
    typer.echo(f"total messages: {total}")
    typer.echo("by status: " + ", ".join(f"{r[0]}={r[1]}" for r in per_status))
    typer.echo("by group: " + ", ".join(f"{r[0]}={r[1]}" for r in per_group))


def main() -> None:
    app()


if __name__ == "__main__":
    main()
