"""Small `.env` editor used by the terminal UI.

The normal runtime still reads configuration through `config.Settings`. This
module only handles the operator-facing edit/save path and intentionally keeps
the first supported surface small: agent backend, native model, and OpenClaw
agent id.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .config import Settings


ENV_PATH = Path(".env")
AGENT_CONFIG_KEYS = (
    "WO_AGENT_BACKEND",
    "WO_LLM_MODEL",
    "WO_OPENCLAW_AGENT_ID",
)


@dataclass(frozen=True)
class AgentRuntimeConfig:
    backend: str
    llm_model: str
    openclaw_agent_id: str
    native_configured: bool = False
    openclaw_token_configured: bool = False
    openclaw_configured: bool = False

    def env_updates(self) -> dict[str, str]:
        return {
            "WO_AGENT_BACKEND": self.backend,
            "WO_LLM_MODEL": self.llm_model,
            "WO_OPENCLAW_AGENT_ID": self.openclaw_agent_id,
        }


def load_agent_runtime_config() -> AgentRuntimeConfig:
    current = Settings()
    return AgentRuntimeConfig(
        backend=(current.agent_backend or "native").lower(),
        llm_model=current.llm_model,
        openclaw_agent_id=current.openclaw_agent_id,
        native_configured=bool(current.llm_api_key),
        openclaw_token_configured=bool(current.openclaw_token),
        openclaw_configured=bool(current.openclaw_token and current.openclaw_agent_id),
    )


def save_agent_runtime_config(
    config: AgentRuntimeConfig,
    *,
    env_path: Path = ENV_PATH,
) -> dict[str, str]:
    updates = _validated_updates(config)
    _update_env_file(env_path, updates)
    return updates


def _validated_updates(config: AgentRuntimeConfig) -> dict[str, str]:
    backend = config.backend.strip().lower()
    llm_model = config.llm_model.strip()
    openclaw_agent_id = config.openclaw_agent_id.strip()
    if backend not in {"native", "openclaw"}:
        raise ValueError("后端只能是 native 或 openclaw")
    if not llm_model:
        raise ValueError("Native 模型不能为空")
    if not openclaw_agent_id:
        raise ValueError("OpenClaw Agent ID 不能为空")
    return {
        "WO_AGENT_BACKEND": backend,
        "WO_LLM_MODEL": llm_model,
        "WO_OPENCLAW_AGENT_ID": openclaw_agent_id,
    }


def _update_env_file(path: Path, updates: dict[str, str]) -> None:
    if path.exists():
        lines = path.read_text(encoding="utf-8").splitlines()
    else:
        lines = [
            "# Generated by `wechat-oracle run`.",
            "# Edit values here or from the terminal UI.",
            "",
        ]
    seen: set[str] = set()
    out: list[str] = []
    for line in lines:
        key = _active_env_key(line)
        if key is None or key not in updates:
            out.append(line)
            continue
        if key in seen:
            continue
        out.append(f"{key}={updates[key]}")
        seen.add(key)
    missing = [key for key in AGENT_CONFIG_KEYS if key in updates and key not in seen]
    if missing and out and out[-1].strip():
        out.append("")
    for key in missing:
        out.append(f"{key}={updates[key]}")
    path.write_text("\n".join(out) + "\n", encoding="utf-8")


def _active_env_key(line: str) -> str | None:
    stripped = line.strip()
    if not stripped or stripped.startswith("#") or "=" not in stripped:
        return None
    return stripped.split("=", 1)[0].strip()
